Support/i18n
LedgerHQ/cex-deposit-live-app pull request #10
Opened 2023-09-15 07:31 UTC by sshmaxime

### 📝 Description

Add internationalization (i18n).

### ❓ Context

- **Linked resource(s)**: `` 

### 📸 Demo

### 🚀 Expectations to reach

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-09-19 16:18 UTC, mcayuelas-ledger commented on __tests__/unit/Home.test.tsx
> +
You can add this in `jest.setup.js` to dispatch it to every test :)

2023-09-20 07:51 UTC, KVNLS requested changes

2023-09-20 07:51 UTC, KVNLS commented on src/i18n/config.ts
> + */
I think that you can remove most of the comments here as it's well described by the code itself.
Example:
```
/**
 * This is the File type. => I have this information by only reading `type File`
 */
export type File = () => Promise<unknown>;
```

2023-09-20 07:51 UTC, KVNLS commented on src/i18n/config.ts
> +    label: "English",
Do we really need the label? I do not see it used anywhere

2023-09-20 07:51 UTC, KVNLS commented on src/i18n/config.ts
> +    file: () => import("./locales/en.json"),
I think that we can have a simpler solution to maintain here with something like this:

```typescript
const PATH = "./locales";

export const LOCALES = {
  FR: "fr",
  EN: "en",
} as const;

export const DEFAULT_LOCALE = LOCALES.EN;

export type Locale = keyof typeof LOCALES;

type LocaleMap = Record<Locale, () => Promise<unknown>>;

export const LocalesI18nConfig: LocaleMap = Object.values(LOCALES).reduce(
  (acc, locale) => ({ ...acc, [locale]: () => import(`${PATH}/${locale}.json`) }),
  {} as LocaleMap,
);
```

That way if I want to add a local I just need to add the file + add the key in LOCALES

2023-09-20 07:51 UTC, KVNLS commented on jest.config.js
> +
I think that we have a tool to manage this with a one liner. You can have a look at my PR on llm Jest

2023-09-20 12:17 UTC, sshmaxime commented on src/i18n/config.ts
> +    file: () => import("./locales/en.json"),
I refactored it but we still need some additional things in order to keep the `t` function typed.

2023-09-20 12:19 UTC, sshmaxime commented on src/i18n/config.ts
> + */
To some extends I agree but comments also brings structure to a file
![Screenshot 2023-09-20 at 14 18 20](https://github.com/LedgerHQ/cex-deposit-live-app/assets/25589782/683aa07c-d64a-4f0a-a906-4e9b48dc1a51)
![Screenshot 2023-09-20 at 14 18 40](https://github.com/LedgerHQ/cex-deposit-live-app/assets/25589782/6d86e3c5-764a-4099-ba8c-53fcfc3ac8ae)

2023-09-20 15:52 UTC, KVNLS requested changes
I think that we can make some improvements on how we add new languages, otherwise, everything looks great to me. Good job!

2023-09-20 15:52 UTC, KVNLS commented on src/i18n/config.ts
> +    file: () => import("./locales/en.json"),
Ok, I understand that TS can't infer a dynamic JSON file so we need to specify all of them. 
I believe that we can have an easier declaration with only one place to declare languages and merge
LOCALES and Locales. We should have only one place where we need to interact when we add a new language otherwise it's error-prone.
Moreover to avoid relying on JS hoisting for declarations and always declare anything we use before usage for readability.
I agree with some comments but still disagree with self-explanatory ones, such as:
```
/**
 * Locale Definition.
 */
```
```
  // Id
  id: Locale;

  // File
  file: File;
```

2023-09-20 15:52 UTC, KVNLS commented on jest.config.js
> +  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths),
🎉

2023-09-20 17:17 UTC, sshmaxime commented
To add languages add the locale in `LOCALES`, typescript will complain, add the necessary info corresponding to the locale in `Locales` and then 🎉

2023-09-21 08:45 UTC, KVNLS approved these changes
Great job!

2023-09-21 08:50 UTC, merged