[SUPPORT] : Add Redux
LedgerHQ/cex-deposit-live-app pull request #12
Opened 2023-09-19 13:04 UTC by mcayuelas-ledger

### 📝 Description

Init Redux Toolkit 

### ❓ Context

- **Linked resource(s)**: `` 

### 📸 Demo

### 🚀 Expectations to reach

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-09-19 14:32 UTC, sshmaxime submitted a review, later dismissed
lgtm ! Maybe i'd add a components that fetches and update the store and add it to the main page

2023-09-20 08:22 UTC, mcayuelas-ledger commented
Adding some Docs !

2023-09-20 08:32 UTC, KVNLS requested changes

2023-09-20 08:32 UTC, KVNLS commented on tools/test.tools.tsx
> +});
You might not do it above the custom render function as here you will define a store that will be shared by all tests and you can have side effects.
Please have a look at the documentation:
You can initiate the store directly as a default value or inside the function. That way you will isolate each test
https://redux.js.org/usage/writing-tests#setting-up-a-reusable-test-render-function
Moreover, we will want to be able to set the store in a specific state: https://redux.js.org/usage/writing-tests#preparing-initial-test-state

2023-09-20 08:32 UTC, KVNLS commented on tools/test.tools.tsx
> +    <Provider store={mockedStore}>
You can rename `mockedStore` as `store` because it's not a mock

2023-09-20 09:14 UTC, KVNLS approved these changes
Looks great!

2023-09-20 09:28 UTC, merged